# http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-file-separation
---
hostname: all

# geerlingguy/firewall
firewall_allowed_tcp_ports:
  - "5044" # Logstash
  - "9092" # Kafka
  - "9200" # Elasticsearch
  - "9300" # Elasticsearch



es_ip: "127.0.0.1"
kafka_ip: "127.0.0.1"
logstash_ip: "127.0.0.1"
kibana_ip: "127.0.0.1"


      
# apolloclark/logstash
logstash:
  version: "6.6.2"
  install_only: true
